# Generated by Django 2.2.4 on 2019-08-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190812_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WomensPost',
        ),
    ]
